const data = [
  {
    prodTitle: "Paracetamol 500mg",
    brand: "Crocin",
    image:
      "https://www.pharmacyonline.co.uk/uploads/images/products/verylarge/pharmacy-online-paracetamol-paracetamol-500mg-100-tablets-1602960473paracetamol-1.jpg",
    price: {
      org: 25.0,
      mrp: 30.0,
      off: 17,
    },
    category: "Pain Relievers",
    expiry: "2026-03-15T00:00:00Z",
  },
  {
    prodTitle: "Cetirizine 10mg",
    brand: "Cetzine",
    image:
      "https://cdn.nhathuoclongchau.com.vn/unsafe/https://cms-prod.s3-sgn09.fptcloud.com/00033097_cetirizin_stada_10mg_10x10_6872_61c9_large_81d9335efe.jpg",
    price: {
      org: 15.0,
      mrp: 20.0,
      off: 25,
    },
    category: "Pain Relievers",
    expiry: "2025-11-20T00:00:00Z",
  },
  {
    prodTitle: "Pantoprazole 40mg",
    brand: "Pantocid",
    image:
      "https://cpimg.tistatic.com/06617387/b/4/Pantoprazole-40-mg-Tablets.jpg",
    price: {
      org: 40.0,
      mrp: 50.0,
      off: 20,
    },
    category: "Pain Relievers",
    expiry: "2026-06-01T00:00:00Z",
  },
  {
    prodTitle: "Amoxicillin 500mg",
    brand: "Mox",
    image:
      "https://api.watsons.com.ph/medias/prdthumb-front-10001747.jpg?context=bWFzdGVyfGltYWdlc3w0MDczMTV8aW1hZ2UvanBlZ3xhRFEyTDJnMlpTOHhNVFExT0RRd09ERTFNekV4T0M5WFZFTlFTQzB4TURBd01UYzBOeTFtY205dWRDNXFjR2N8YTEyMDcxNzcxYjM4NDJhM2FhMDJmNWM0NjhiMDdjNDFjMDM4MjEwODVhY2MwNjUzZjI5MDQ3YTdhOGIxYzhmMg",
    price: {
      org: 75.0,
      mrp: 90.0,
      off: 17,
    },
    category: "Pain Relievers",
    expiry: "2025-09-30T00:00:00Z",
  },
  {
    prodTitle: "Ibuprofen 400mg",
    brand: "Brufen",
    image:
      "https://5.imimg.com/data5/SELLER/Default/2023/6/319597573/MH/NE/SR/135658020/ibuprofen-400-mg-bp-tablets-500x500.jpg",
    price: {
      org: 20.0,
      mrp: 25.0,
      off: 20,
    },
    category: "Pain Relievers",
    expiry: "2026-01-10T00:00:00Z",
  },
  {
    prodTitle: "Azithromycin 250mg",
    brand: "Azithral",
    image:
      "https://img3.exportersindia.com/product_images/bc-full/2023/1/8794577/azithromycin-tablet-1674622200-6733765.png",
    price: {
      org: 120.0,
      mrp: 135.0,
      off: 11,
    },
    category: "Pain Relievers",
    expiry: "2025-12-15T00:00:00Z",
  },
  {
    prodTitle: "Loratadine 10mg",
    brand: "Claritin",
    image:
      "https://img1.exportersindia.com/product_images/bc-full/2024/11/13747853/watermark/loratadine-10-mg-tablet-1731480767-7681918.jpeg",
    price: {
      org: 22.0,
      mrp: 28.0,
      off: 21,
    },
    category: "Pain Relievers",
    expiry: "2026-04-05T00:00:00Z",
  },
  {
    prodTitle: "Ranitidine 150mg",
    brand: "Zinetac",
    image:
      "https://ryvispharma.com/wp-content/uploads/2020/12/578-4-480x446.jpg",
    price: {
      org: 18.0,
      mrp: 22.0,
      off: 18,
    },
    category: "Pain Relievers",
    expiry: "2025-10-18T00:00:00Z",
  },
  {
    prodTitle: "Vitamin C 500mg",
    brand: "Limcee",
    image:
      "https://th.bing.com/th/id/R.ec3de068f1589fa857ed52307cc07113?rik=Bp9jfvEKhlB4uA&riu=http%3a%2f%2fproduct.hstatic.net%2f200000142961%2fproduct%2f4860da76cc3c4891b1ca1714c15a3005_e4fe442a960c453193da08dc816583ab_grande.jpg&ehk=oVkCX1CJOKguLYgXSkgMWzUhP24XUV2ehR2g11Gy5FE%3d&risl=&pid=ImgRaw&r=0",
    price: {
      org: 30.0,
      mrp: 35.0,
      off: 14,
    },
    category: "Pain Relievers",
    expiry: "2026-07-20T00:00:00Z",
  },
  {
    prodTitle: "Montelukast 10mg",
    brand: "Montair",
    image:
      "https://mcareexports.com/wp-content/uploads/2021/07/singulair-10mg-tab.jpg",
    price: {
      org: 60.0,
      mrp: 70.0,
      off: 14,
    },
    category: "Pain Relievers",
    expiry: "2025-08-12T00:00:00Z",
  },
  {
    prodTitle: "AloeVera Moisturizing Cream",
    brand: "DermaSoft",
    image:
      "https://img.freepik.com/premium-vector/moisturizing-face-cream-serum-body-lotion-with-aloe-vera-extract_352822-73.jpg?w=2000",
    price: { org: 250, mrp: 300, off: 17 },
    expiry: "2026-01-01",
    category: "Skin Care",
    desc: "Hydrating cream with natural aloe vera extract.",
    benefits: ["Hydrates skin", "Soothes inflammation"],
    ingredients: ["Aloe Vera", "Vitamin E", "Glycerin"],
    uses: ["Dry skin", "Sunburn relief"],
    sideEffects: ["Rare allergic reaction"],
    direction: "Apply twice daily on clean skin.",
  },
  {
    prodTitle: "AcneControl Face Wash",
    brand: "ClearGlow",
    image:
      "https://cdn.shopify.com/s/files/1/0272/4714/9155/products/himalaya-men-pimple-clear-neem-face-wash_2e198848-2f7c-414c-aa22-b88c0ff6fa92.jpg?v=1648206318",
    price: { org: 180, mrp: 220, off: 18 },
    expiry: "2025-12-01",
    category: "Skin Care",
    desc: "Anti-acne face wash with salicylic acid.",
    benefits: ["Reduces pimples", "Cleans pores"],
    ingredients: ["Salicylic Acid", "Tea Tree Oil"],
    uses: ["Acne-prone skin"],
    sideEffects: ["Dryness"],
    direction: "Use daily, morning and night.",
  },
  {
    prodTitle: "SPF 50 Sunscreen Lotion",
    brand: "SunGuard",
    image:
      "https://m237.apollo247.com/pub/media/catalog/product/L/A/LAC0550_1-AUG23_1.jpg",
    price: { org: 399, mrp: 450, off: 11 },
    expiry: "2025-11-20",
    category: "Skin Care",
    desc: "Water-resistant sunscreen with broad spectrum protection.",
    benefits: ["UV protection", "Non-greasy finish"],
    ingredients: ["Zinc Oxide", "Aloe Vera", "SPF 50"],
    uses: ["Sunburn prevention"],
    sideEffects: ["None reported"],
    direction: "Apply 15 mins before sun exposure.",
  },
  {
    prodTitle: "Night Repair Serum",
    brand: "GlowRevive",
    image:
      "https://www.sephora.fr/on/demandware.static/-/Sites-masterCatalog_Sephora/default/dwe2f3e654/images/hi-res/SKU/SKU_1646/521863_swatch.jpg",
    price: { org: 799, mrp: 999, off: 20 },
    expiry: "2026-06-30",
    category: "Skin Care",
    desc: "Advanced serum to repair skin overnight.",
    benefits: ["Reduces wrinkles", "Brightens skin"],
    ingredients: ["Retinol", "Peptides", "Niacinamide"],
    uses: ["Anti-aging"],
    sideEffects: ["Mild tingling"],
    direction: "Apply at night before moisturizer.",
  },
  {
    prodTitle: "Charcoal Peel-off Mask",
    brand: "PureSkin",
    image:
      "https://th.bing.com/th/id/R.f821c755c6935f81bca0e901a64b6645?rik=lX3%2fJ%2bzNw5Kv3A&riu=http%3a%2f%2fwww.thenaturalwash.com%2fcdn%2fshop%2ffiles%2fproduct-_-ingredients_00fe2370-7a27-44bb-abf9-35a8d5f28930.jpg%3fv%3d1687949058&ehk=8ewf9P1nlFS%2f7qGcqYVReomCt7dy8b37TTpqiUADDtg%3d&risl=&pid=ImgRaw&r=0",
    price: { org: 299, mrp: 349, off: 14 },
    expiry: "2025-09-15",
    category: "Skin Care",
    desc: "Detoxifying charcoal peel-off face mask.",
    benefits: ["Removes blackheads", "Detoxifies skin"],
    ingredients: ["Activated Charcoal", "Aloe Vera"],
    uses: ["Blackhead removal"],
    sideEffects: ["Tingling sensation"],
    direction: "Apply evenly and peel after 15 minutes.",
  },
  {
    prodTitle: "Whey Protein Isolate - Chocolate",
    brand: "ProBody",
    image:
      "https://th.bing.com/th/id/OIP.ZVvIQXvpPFdkoZdAMZaOKQHaHa?rs=1&pid=ImgDetMain",
    price: { org: 1299, mrp: 1499, off: 13 },
    expiry: "2026-04-01",
    category: "Protein & Vitamins",
    desc: "High-quality whey protein isolate for muscle growth.",
    benefits: ["Builds muscle", "Supports recovery"],
    ingredients: ["Whey Protein Isolate", "Cocoa", "Digestive Enzymes"],
    uses: ["Post workout"],
    sideEffects: ["None if taken as directed"],
    direction: "Mix 1 scoop with 200ml water after workout.",
  },
  {
    prodTitle: "Multivitamin Tablets for Men",
    brand: "HealthPlus",
    image:
      "https://th.bing.com/th/id/OIP.ASYeFCScOrXrlnd5gReQXAHaHa?rs=1&pid=ImgDetMain",
    price: { org: 499, mrp: 599, off: 17 },
    expiry: "2026-03-01",
    category: "Protein & Vitamins",
    desc: "Daily multivitamin tablets for overall health.",
    benefits: ["Energy boost", "Supports immunity"],
    ingredients: ["Vitamin A-Z", "Zinc", "Magnesium"],
    uses: ["General wellness"],
    sideEffects: ["None reported"],
    direction: "Take 1 tablet daily after breakfast.",
  },
  {
    prodTitle: "Vitamin C Effervescent Tablets",
    brand: "NutriFizz",
    image:
      "https://cdn.fcglcdn.com/brainbees/images/products/583x720/12240818a.webp",
    price: { org: 299, mrp: 349, off: 14 },
    expiry: "2025-10-01",
    category: "Protein & Vitamins",
    desc: "Boosts immunity and antioxidant support.",
    benefits: ["Improves immunity", "Antioxidant support"],
    ingredients: ["Vitamin C", "Zinc"],
    uses: ["Cold prevention"],
    sideEffects: ["None"],
    direction: "Dissolve 1 tablet in water daily.",
  },
  {
    prodTitle: "Biotin Gummies for Hair & Nails",
    brand: "GlamCare",
    image: "https://m.media-amazon.com/images/I/71AWJKemTOL._AC_.jpg",
    price: { org: 699, mrp: 799, off: 12 },
    expiry: "2026-01-01",
    category: "Protein & Vitamins",
    desc: "Tasty gummies that support hair and nail health.",
    benefits: ["Hair growth", "Nail strength"],
    ingredients: ["Biotin", "Folic Acid", "Vitamin B12"],
    uses: ["Hair and nail care"],
    sideEffects: ["None reported"],
    direction: "Chew 1 gummy per day.",
  },
  {
    prodTitle: "Plant-Based Protein Powder - Vanilla",
    brand: "GreenFuel",
    image:
      "https://i5.walmartimages.com/asr/ec61c99f-da8b-45d1-bd2e-512810584b83_1.4c4e26539c65e4e249781ed5ec88dd85.jpeg",
    price: { org: 999, mrp: 1199, off: 16 },
    expiry: "2026-02-15",
    category: "Protein & Vitamins",
    desc: "Vegan-friendly protein supplement.",
    benefits: ["Muscle recovery", "Plant protein"],
    ingredients: ["Pea Protein", "Brown Rice Protein", "Vanilla"],
    uses: ["Fitness nutrition"],
    sideEffects: ["May cause gas initially"],
    direction: "Mix with water or milk post workout.",
  },
];

export default data;
